/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.praktikum02072026;

/**
 *
 * @author dhiii
 */
public class MenuMinuman extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuMinuman.class.getName());

    /**
     * Creates new form MenuMinuman
     */
    public MenuMinuman() {
        initComponents();
    }
    private cafe utama;

    public MenuMinuman(cafe utama) {
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkMangga = new javax.swing.JRadioButton();
        chkSirsak = new javax.swing.JRadioButton();
        chkPower = new javax.swing.JRadioButton();
        txtMangga = new javax.swing.JTextField();
        txtSirsak = new javax.swing.JTextField();
        txtPower = new javax.swing.JTextField();
        cbMangga = new javax.swing.JComboBox<>();
        cbSirsak = new javax.swing.JComboBox<>();
        cbPower = new javax.swing.JComboBox<>();
        txtTotalMangga = new javax.swing.JTextField();
        txtTotalSirsak = new javax.swing.JTextField();
        txtTotalPower = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PILIHAN MENU MINUMAN");

        chkMangga.setText("Jus Mangga");
        chkMangga.addActionListener(this::chkManggaActionPerformed);

        chkSirsak.setText("Jus Sirsak");
        chkSirsak.addActionListener(this::chkSirsakActionPerformed);

        chkPower.setText("Power F");
        chkPower.addActionListener(this::chkPowerActionPerformed);

        txtMangga.setText("0");

        txtSirsak.setText("0");

        txtPower.setText("0");

        cbMangga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMangga.addActionListener(this::cbManggaActionPerformed);

        cbSirsak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbSirsak.addActionListener(this::cbSirsakActionPerformed);

        cbPower.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbPower.addActionListener(this::cbPowerActionPerformed);

        txtTotalMangga.setText("0");

        txtTotalSirsak.setText("0");

        txtTotalPower.setText("0");

        btnTotal.setText("Total");
        btnTotal.addActionListener(this::btnTotalActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        txtTotal.setText("0");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkSirsak, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkMangga, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkPower, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMangga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSirsak, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPower, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMangga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSirsak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTotal)
                            .addComponent(btnReset))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKembali)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalPower, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalSirsak, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalMangga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel1)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMangga)
                    .addComponent(txtMangga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMangga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMangga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSirsak)
                    .addComponent(txtSirsak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSirsak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalSirsak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPower)
                    .addComponent(txtPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKembali))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkManggaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkManggaActionPerformed
        txtMangga.setText("10000");
    }//GEN-LAST:event_chkManggaActionPerformed

    private void chkSirsakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSirsakActionPerformed
       txtSirsak.setText("10000");
    }//GEN-LAST:event_chkSirsakActionPerformed

    private void chkPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPowerActionPerformed
        txtPower.setText("8000");
    }//GEN-LAST:event_chkPowerActionPerformed

    private void cbManggaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbManggaActionPerformed
        int jumlah = cbMangga.getSelectedIndex();
        double harga = Double.parseDouble(txtMangga.getText());
        double total = jumlah * harga;
        txtTotalMangga.setText(Double.toString(total));

    }//GEN-LAST:event_cbManggaActionPerformed

    private void cbSirsakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSirsakActionPerformed
       int jumlah = cbSirsak.getSelectedIndex();
        double harga = Double.parseDouble(txtSirsak.getText());
        double total = jumlah * harga;
        txtTotalSirsak.setText(Double.toString(total));
    }//GEN-LAST:event_cbSirsakActionPerformed

    private void cbPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPowerActionPerformed
        int jumlah = cbPower.getSelectedIndex();
        double harga = Double.parseDouble(txtPower.getText());
        double total = jumlah * harga;
        txtTotalPower.setText(Double.toString(total));
    }//GEN-LAST:event_cbPowerActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double mangga = Double.parseDouble(txtTotalMangga.getText());
        double sirsak = Double.parseDouble(txtTotalSirsak.getText());
        double power = Double.parseDouble(txtTotalPower.getText());
        double total = mangga + sirsak + power;
        txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtMangga.setText("0");
        txtSirsak.setText("0");
        txtPower.setText("0");

        txtTotalMangga.setText("0");
        txtTotalSirsak.setText("0");
        txtTotalPower.setText("0");

        txtTotal.setText("0");

        cbMangga.setSelectedIndex(0);
        cbSirsak.setSelectedIndex(0);
        cbPower.setSelectedIndex(0);

        chkMangga.setSelected(false);
        chkSirsak.setSelected(false);
        chkPower.setSelected(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotal.getText();
        utama.setTotalMinuman(total);
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuMinuman().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbMangga;
    private javax.swing.JComboBox<String> cbPower;
    private javax.swing.JComboBox<String> cbSirsak;
    private javax.swing.JRadioButton chkMangga;
    private javax.swing.JRadioButton chkPower;
    private javax.swing.JRadioButton chkSirsak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtMangga;
    private javax.swing.JTextField txtPower;
    private javax.swing.JTextField txtSirsak;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalMangga;
    private javax.swing.JTextField txtTotalPower;
    private javax.swing.JTextField txtTotalSirsak;
    // End of variables declaration//GEN-END:variables
}
